collection_name: rag
chrome_db_dir: data/chroma_db
data_path: data/raw
md5_hex_store: data/md5.txt
allow_types: ['txt', 'pdf', 'csv', 'tsv', '.md', '.markdown']

chunk_size: 500
chunk_overlap: 50
top_k: 4
similarity_threshold: 0.7
separators: ['\n\n', '\n', '.', ',', '?', '!', '，', '。', '？', '！', ' ', '']

